# Generated by Django 4.1.1 on 2022-12-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Centros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=12)),
                ("img", models.CharField(max_length=6000)),
                ("latitud", models.DecimalField(decimal_places=18, max_digits=36)),
                ("longitud", models.DecimalField(decimal_places=18, max_digits=36)),
            ],
        ),
        migrations.CreateModel(
            name="Incidentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("img", models.CharField(max_length=6000)),
                ("latitud", models.DecimalField(decimal_places=18, max_digits=36)),
                ("longitud", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="friendship.categoria",
                    ),
                ),
            ],
        ),
    ]
